/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package svm.view.forms;

import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import svm.rmi.abstraction.factory.IRMIControllerFactory;
import svm.view.controller.ViewContestController;
import svm.view.controller.ViewMemberController;

/**
 *
 * @author Patrick
 */
public class PanelContests extends javax.swing.JPanel {

      private ViewContestController viewContestController;
    
    
    /**
     * Creates new Form Panel for Contest UseCases
     */
    public PanelContests() {
         this.viewContestController = new ViewContestController(this);
        initComponents();

    }

    /**
     * Getters and Setters for Components on Panel Contest *
     */
    public JButton getBtnAddToContest() {
        return btnAddToContest;
    }

    public JButton getBtnAddToSubTeam() {
        return btnAddToSubTeam;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnConfirmContestTeams() {
        return btnConfirmContestTeams;
    }

    public JButton getBtnConfirmSubTeam() {
        return btnConfirmSubTeam;
    }

    public JButton getBtnContestNew() {
        return btnContestNew;
    }


    public JButton getBtnContestSave() {
        return btnContestSave;
    }

    public JButton getBtnRemoveFromContest() {
        return btnRemoveFromContest;
    }

    public JButton getBtnRemoveFromSubTeam() {
        return btnRemoveFromSubTeam;
    }

    public JButton getBtnToA() {
        return btnToA;
    }

    public JButton getBtnToB() {
        return btnToB;
    }

    public JComboBox getCmbContestContactDetails() {
        return cmbContestContactDetails;
    }


    public JComboBox getCmbContestTeams() {
        return cmbContestTeams;
    }

   
    public JDateChooser getDcContestEndDate() {
        return dcContestEndDate;
    }

   

    public JDateChooser getDcContestStartDate() {
        return dcContestStartDate;
    }

    public JList getListboxAllContestTeams() {
        return listboxAllContestTeams;
    }

    public JList getListboxAllTeamMembers() {
        return listboxAllTeamMembers;
    }

    public JList getListboxAllTeamsInSport() {
        return listboxAllTeamsInSport;
    }

    public JList getListboxContestTeamMembers() {
        return listboxContestTeamMembers;
    }

    public JList getListboxContestTeams() {
        return listboxContestTeams;
    }

    public JList getListboxShowContests() {
        return listboxShowContests;
    }

    public JList getListboxTeamA() {
        return listboxTeamA;
    }

    public JList getListboxTeamB() {
        return listboxTeamB;
    }

    public JTable getTableMatchesOverview() {
        return tableMatchesOverview;
    }

    public JTextField getTfContestFee() {
        return tfContestFee;
    }

    public JTextField getTfContestID() {
        return tfContestID;
    }

    public JTextField getTfContestMail1() {
        return tfContestMail1;
    }

    public JTextField getTfContestMail2() {
        return tfContestMail2;
    }

    public JTextField getTfContestName() {
        return tfContestName;
    }

    public JTextField getTfContestPhone1() {
        return tfContestPhone1;
    }

    public JTextField getTfContestPhone2() {
        return tfContestPhone2;
    }

    public JTextField getTfContestStreet() {
        return tfContestStreet;
    }

    public JTextField getTfContestStreetNumber() {
        return tfContestStreetNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanelContest = new javax.swing.JSplitPane();
        panelContestLeft = new javax.swing.JPanel();
        splitPanelMembersLeft = new javax.swing.JSplitPane();
        panelMembersSearch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btShowAllContests = new javax.swing.JButton();
        panelMembersList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listboxShowContests = new javax.swing.JList();
        splitPanelContestRight = new javax.swing.JPanel();
        panelContestMenu = new javax.swing.JPanel();
        btnContestNew = new javax.swing.JButton();
        btnContestSave = new javax.swing.JButton();
        panelContestHead = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfContestFee = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfContestID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfContestName = new javax.swing.JTextField();
        dcContestStartDate = new com.toedter.calendar.JDateChooser();
        dcContestEndDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tabPanelContestDetails = new javax.swing.JTabbedPane();
        panelContestLocation = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfContestPhone1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfContestPhone2 = new javax.swing.JTextField();
        tfContestMail1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfContestMail2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfContestStreet = new javax.swing.JTextField();
        tfContestStreetNumber = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbContestContactDetails = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        panelContestTeams = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        listboxContestTeams = new javax.swing.JList();
        btnConfirmContestTeams = new javax.swing.JButton();
        btnRemoveFromContest = new javax.swing.JButton();
        btnAddToContest = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        listboxAllTeamsInSport = new javax.swing.JList();
        jLabel29 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        panelContestSubTeams = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cmbContestTeams = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        listboxAllTeamMembers = new javax.swing.JList();
        jLabel35 = new javax.swing.JLabel();
        btnRemoveFromSubTeam = new javax.swing.JButton();
        btnAddToSubTeam = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        listboxContestTeamMembers = new javax.swing.JList();
        btnConfirmSubTeam = new javax.swing.JButton();
        panelContestTeamsAlternate = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listboxAllContestTeams = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listboxTeamA = new javax.swing.JList();
        jLabel33 = new javax.swing.JLabel();
        btnToA = new javax.swing.JButton();
        btnToB = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listboxTeamB = new javax.swing.JList();
        jLabel39 = new javax.swing.JLabel();
        panelContestResults = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableMatchesOverview = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        btnMatchOverviewSave = new javax.swing.JButton();

        splitPanelContest.setBackground(new java.awt.Color(252, 252, 252));
        splitPanelContest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        splitPanelContest.setDividerLocation(354);
        splitPanelContest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        splitPanelContest.setDoubleBuffered(true);

        panelContestLeft.setBackground(new java.awt.Color(252, 252, 252));
        panelContestLeft.setPreferredSize(new java.awt.Dimension(352, 500));

        splitPanelMembersLeft.setDividerLocation(60);
        splitPanelMembersLeft.setDividerSize(4);
        splitPanelMembersLeft.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPanelMembersLeft.setDoubleBuffered(true);
        splitPanelMembersLeft.setPreferredSize(new java.awt.Dimension(352, 500));

        panelMembersSearch.setPreferredSize(new java.awt.Dimension(350, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Aktuelle Wetbewerbe");
        jLabel1.setToolTipText("");

        btShowAllContests.setText("Alle Wettbewerbe anzeigen");
        btShowAllContests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowAllContestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMembersSearchLayout = new javax.swing.GroupLayout(panelMembersSearch);
        panelMembersSearch.setLayout(panelMembersSearchLayout);
        panelMembersSearchLayout.setHorizontalGroup(
            panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(128, 128, 128))
            .addComponent(btShowAllContests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMembersSearchLayout.setVerticalGroup(
            panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btShowAllContests))
        );

        splitPanelMembersLeft.setTopComponent(panelMembersSearch);

        panelMembersList.setBackground(new java.awt.Color(252, 252, 252));

        jScrollPane1.setBorder(null);
        jScrollPane1.setDoubleBuffered(true);

        listboxShowContests.setBackground(new java.awt.Color(252, 252, 252));
        listboxShowContests.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        listboxShowContests.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxShowContests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxShowContests.setDoubleBuffered(true);
        listboxShowContests.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxShowContestsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listboxShowContests);

        javax.swing.GroupLayout panelMembersListLayout = new javax.swing.GroupLayout(panelMembersList);
        panelMembersList.setLayout(panelMembersListLayout);
        panelMembersListLayout.setHorizontalGroup(
            panelMembersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        panelMembersListLayout.setVerticalGroup(
            panelMembersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMembersListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        splitPanelMembersLeft.setRightComponent(panelMembersList);

        javax.swing.GroupLayout panelContestLeftLayout = new javax.swing.GroupLayout(panelContestLeft);
        panelContestLeft.setLayout(panelContestLeftLayout);
        panelContestLeftLayout.setHorizontalGroup(
            panelContestLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanelMembersLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelContestLeftLayout.setVerticalGroup(
            panelContestLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestLeftLayout.createSequentialGroup()
                .addComponent(splitPanelMembersLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );

        splitPanelContest.setLeftComponent(panelContestLeft);

        splitPanelContestRight.setBackground(new java.awt.Color(252, 252, 252));
        splitPanelContestRight.setPreferredSize(new java.awt.Dimension(590, 500));

        panelContestMenu.setBackground(new java.awt.Color(170, 216, 170));
        panelContestMenu.setForeground(new java.awt.Color(255, 255, 255));

        btnContestNew.setText("Neuer Eintrag");
        btnContestNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContestNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContestNewActionPerformed(evt);
            }
        });

        btnContestSave.setText("Save");
        btnContestSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContestSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContestSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContestMenuLayout = new javax.swing.GroupLayout(panelContestMenu);
        panelContestMenu.setLayout(panelContestMenuLayout);
        panelContestMenuLayout.setHorizontalGroup(
            panelContestMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnContestSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContestNew, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContestMenuLayout.setVerticalGroup(
            panelContestMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContestMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnContestNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContestSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelContestHead.setBackground(new java.awt.Color(252, 252, 252));
        panelContestHead.setPreferredSize(new java.awt.Dimension(560, 128));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ende");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Teilnahmebetrag");

        tfContestID.setText("4848");
        tfContestID.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Wettbewerbnr.");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("€");

        dcContestStartDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcContestStartDatePropertyChange(evt);
            }
        });

        dcContestEndDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcContestEndDatePropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Beginn");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bezeichnung");

        javax.swing.GroupLayout panelContestHeadLayout = new javax.swing.GroupLayout(panelContestHead);
        panelContestHead.setLayout(panelContestHeadLayout);
        panelContestHeadLayout.setHorizontalGroup(
            panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestHeadLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcContestStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfContestFee, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(panelContestHeadLayout.createSequentialGroup()
                        .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelContestHeadLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcContestEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfContestID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelContestHeadLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfContestName)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelContestHeadLayout.setVerticalGroup(
            panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestHeadLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfContestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfContestFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel5)
                        .addComponent(jLabel19))
                    .addComponent(dcContestStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfContestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(dcContestEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tabPanelContestDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabPanelContestDetails.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPanelContestDetailsStateChanged(evt);
            }
        });

        panelContestLocation.setBackground(new java.awt.Color(252, 252, 252));
        panelContestLocation.setPreferredSize(new java.awt.Dimension(572, 349));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Primäre Adresse und Kontaktdetails");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Telefon 1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Telefon 2");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Email 1");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Email 2");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Straße");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nr.");

        cmbContestContactDetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmbContestContactDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbContestContactDetails.setFocusCycleRoot(true);
        cmbContestContactDetails.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbContestContactDetailsItemStateChanged(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Adressen");

        javax.swing.GroupLayout panelContestLocationLayout = new javax.swing.GroupLayout(panelContestLocation);
        panelContestLocation.setLayout(panelContestLocationLayout);
        panelContestLocationLayout.setHorizontalGroup(
            panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestLocationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContestLocationLayout.createSequentialGroup()
                        .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContestPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfContestPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContestLocationLayout.createSequentialGroup()
                        .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContestMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfContestMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContestLocationLayout.createSequentialGroup()
                        .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContestStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfContestStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContestLocationLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbContestContactDetails, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        panelContestLocationLayout.setVerticalGroup(
            panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestLocationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContestPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContestPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContestMail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContestMail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContestStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContestStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContestLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbContestContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        tabPanelContestDetails.addTab("Location", panelContestLocation);

        panelContestTeams.setBackground(new java.awt.Color(252, 252, 252));

        listboxContestTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxContestTeams.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxContestTeamsValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(listboxContestTeams);

        btnConfirmContestTeams.setText("Wettkampfteams einladen");
        btnConfirmContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmContestTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmContestTeamsActionPerformed(evt);
            }
        });

        btnRemoveFromContest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoveFromContest.setText("<<");
        btnRemoveFromContest.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnRemoveFromContest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromContestActionPerformed(evt);
            }
        });

        btnAddToContest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddToContest.setText(">>");
        btnAddToContest.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnAddToContest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToContestActionPerformed(evt);
            }
        });

        listboxAllTeamsInSport.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxAllTeamsInSport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxAllTeamsInSport.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxAllTeamsInSportValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(listboxAllTeamsInSport);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Teams zum Wettkampf zuteilen");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Alle Teams");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Teams im Wettkampf");

        javax.swing.GroupLayout panelContestTeamsLayout = new javax.swing.GroupLayout(panelContestTeams);
        panelContestTeams.setLayout(panelContestTeamsLayout);
        panelContestTeamsLayout.setHorizontalGroup(
            panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContestTeamsLayout.createSequentialGroup()
                        .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemoveFromContest, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddToContest, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirmContestTeams))
                            .addComponent(jLabel38))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelContestTeamsLayout.setVerticalGroup(
            panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContestTeamsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel29)
                .addGap(43, 43, 43)
                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(panelContestTeamsLayout.createSequentialGroup()
                        .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmContestTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                                .addComponent(btnAddToContest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveFromContest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabPanelContestDetails.addTab("Teams", panelContestTeams);

        panelContestSubTeams.setBackground(new java.awt.Color(252, 252, 252));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Team für den Wettkampf zusammenstellen");

        cmbContestTeams.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmbContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbContestTeams.setFocusCycleRoot(true);
        cmbContestTeams.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbContestTeamsItemStateChanged(evt);
            }
        });

        listboxAllTeamMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxAllTeamMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxAllTeamMembers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxAllTeamMembersValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(listboxAllTeamMembers);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Alle Teammitglieder");

        btnRemoveFromSubTeam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoveFromSubTeam.setText("<<");
        btnRemoveFromSubTeam.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnRemoveFromSubTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromSubTeamActionPerformed(evt);
            }
        });

        btnAddToSubTeam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddToSubTeam.setText(">>");
        btnAddToSubTeam.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnAddToSubTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToSubTeamActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Wettkampfteam");

        listboxContestTeamMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxContestTeamMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxContestTeamMembers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxContestTeamMembersValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(listboxContestTeamMembers);

        btnConfirmSubTeam.setText("Wettkampfteam speichern");
        btnConfirmSubTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmSubTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSubTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContestSubTeamsLayout = new javax.swing.GroupLayout(panelContestSubTeams);
        panelContestSubTeams.setLayout(panelContestSubTeamsLayout);
        panelContestSubTeamsLayout.setHorizontalGroup(
            panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                        .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbContestTeams, javax.swing.GroupLayout.Alignment.LEADING, 0, 161, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemoveFromSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddToSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirmSubTeam)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelContestSubTeamsLayout.setVerticalGroup(
            panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbContestTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                        .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                                .addComponent(btnAddToSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveFromSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabPanelContestDetails.addTab("Wettkampfteilnehmer", panelContestSubTeams);

        panelContestTeamsAlternate.setBackground(new java.awt.Color(252, 252, 252));
        panelContestTeamsAlternate.setPreferredSize(new java.awt.Dimension(950, 364));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Wettkampf-Matches einteilen");

        listboxAllContestTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxAllContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxAllContestTeams.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxAllContestTeamsValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(listboxAllContestTeams);

        listboxTeamA.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxTeamA.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxTeamAValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listboxTeamA);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Team A");

        btnToA.setText(">> A");
        btnToA.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnToA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToAActionPerformed(evt);
            }
        });

        btnToB.setText(">> B");
        btnToB.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnToB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToBActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Team B");

        btnBack.setText("<<");
        btnBack.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        listboxTeamB.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxTeamB.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxTeamBValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(listboxTeamB);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Alle Teams im Wettkampf");

        javax.swing.GroupLayout panelContestTeamsAlternateLayout = new javax.swing.GroupLayout(panelContestTeamsAlternate);
        panelContestTeamsAlternate.setLayout(panelContestTeamsAlternateLayout);
        panelContestTeamsAlternateLayout.setHorizontalGroup(
            panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnToB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnToA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(578, 578, 578))
        );
        panelContestTeamsAlternateLayout.setVerticalGroup(
            panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addGap(39, 39, 39)
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                        .addComponent(btnToA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnToB)
                        .addGap(44, 44, 44)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabPanelContestDetails.addTab("Matcheinteilung", panelContestTeamsAlternate);

        panelContestResults.setBackground(new java.awt.Color(252, 252, 252));

        tableMatchesOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Team A", "Team B", "Score A", "Score B"
            }
        ));
        tableMatchesOverview.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jScrollPane8.setViewportView(tableMatchesOverview);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Matchübersicht und Resultate");

        btnMatchOverviewSave.setText("Matchübersicht speichern");
        btnMatchOverviewSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatchOverviewSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchOverviewSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContestResultsLayout = new javax.swing.GroupLayout(panelContestResults);
        panelContestResults.setLayout(panelContestResultsLayout);
        panelContestResultsLayout.setHorizontalGroup(
            panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestResultsLayout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMatchOverviewSave))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        panelContestResultsLayout.setVerticalGroup(
            panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestResultsLayout.createSequentialGroup()
                .addGroup(panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestResultsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel30))
                    .addGroup(panelContestResultsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMatchOverviewSave, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanelContestDetails.addTab("Matchübersicht", panelContestResults);

        javax.swing.GroupLayout splitPanelContestRightLayout = new javax.swing.GroupLayout(splitPanelContestRight);
        splitPanelContestRight.setLayout(splitPanelContestRightLayout);
        splitPanelContestRightLayout.setHorizontalGroup(
            splitPanelContestRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContestMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPanelContestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(splitPanelContestRightLayout.createSequentialGroup()
                .addComponent(panelContestHead, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        splitPanelContestRightLayout.setVerticalGroup(
            splitPanelContestRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splitPanelContestRightLayout.createSequentialGroup()
                .addComponent(panelContestMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContestHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanelContestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPanelContest.setRightComponent(splitPanelContestRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanelContest, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanelContest, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContestSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContestSaveActionPerformed
             viewContestController.saveContest();
    }//GEN-LAST:event_btnContestSaveActionPerformed

    private void btnContestNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContestNewActionPerformed
            viewContestController.createNewContest();
    }//GEN-LAST:event_btnContestNewActionPerformed

    private void listboxShowContestsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxShowContestsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxShowContestsValueChanged

    private void tabPanelContestDetailsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPanelContestDetailsStateChanged
       if(tabPanelContestDetails.getSelectedIndex() == 0){
           viewContestController.showAllLocations();
       }else if(tabPanelContestDetails.getSelectedIndex() == 1){
           viewContestController.showAllTeams();
       }else if(tabPanelContestDetails.getSelectedIndex() == 2){
           //TODO
       }else if(tabPanelContestDetails.getSelectedIndex() == 3){
           //TODO
       }else if(tabPanelContestDetails.getSelectedIndex() == 4){
           viewContestController.showMatchOverview();
       }
    }//GEN-LAST:event_tabPanelContestDetailsStateChanged

    private void cmbContestContactDetailsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbContestContactDetailsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbContestContactDetailsItemStateChanged

    private void btnAddToContestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToContestActionPerformed
        viewContestController.addTeamToContest();
    }//GEN-LAST:event_btnAddToContestActionPerformed

    private void btnRemoveFromContestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromContestActionPerformed
        viewContestController.removeTeamFromContest();
    }//GEN-LAST:event_btnRemoveFromContestActionPerformed

    private void btnConfirmContestTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmContestTeamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmContestTeamsActionPerformed

    private void cmbContestTeamsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbContestTeamsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbContestTeamsItemStateChanged

    private void btnConfirmSubTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSubTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmSubTeamActionPerformed

    private void btnAddToSubTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToSubTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddToSubTeamActionPerformed

    private void btnRemoveFromSubTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromSubTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveFromSubTeamActionPerformed

    private void btnToAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToAActionPerformed

    private void btnToBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToBActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void listboxAllContestTeamsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxAllContestTeamsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxAllContestTeamsValueChanged

    private void listboxTeamAValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxTeamAValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxTeamAValueChanged

    private void listboxTeamBValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxTeamBValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxTeamBValueChanged

    private void listboxAllTeamMembersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxAllTeamMembersValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxAllTeamMembersValueChanged

    private void listboxContestTeamMembersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxContestTeamMembersValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxContestTeamMembersValueChanged

    private void listboxAllTeamsInSportValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxAllTeamsInSportValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxAllTeamsInSportValueChanged

    private void listboxContestTeamsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxContestTeamsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxContestTeamsValueChanged

    private void dcContestStartDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcContestStartDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dcContestStartDatePropertyChange

    private void dcContestEndDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcContestEndDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dcContestEndDatePropertyChange

    private void btnMatchOverviewSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchOverviewSaveActionPerformed
        int i = 0;
        LinkedList dates = new LinkedList();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy - hh.mm");
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, -100);
        sdf.set2DigitYearStart(cal.getTime());

        while (i < tableMatchesOverview.getModel().getRowCount()) {
            String dateString = (String) tableMatchesOverview.getValueAt(i, 0);

            try {
                Date date = sdf.parse(dateString);
                dates.add(date);
            } catch (ParseException ex) {
                Logger.getLogger(PanelContests.class.getName()).log(Level.SEVERE, null, ex);
                javax.swing.JOptionPane.showMessageDialog(this, "Error while parsing Date, corrupted cell: " + i + ",0\nCorrect Format is dd.MM.yyyy - hh.mm");
                dates.clear();
                break;
            }
            i++;
            System.out.println("Success");
        }
        i = 0;
        LinkedList TeamA = new LinkedList();
        while (i < tableMatchesOverview.getModel().getRowCount()) {
            if (tableMatchesOverview.getValueAt(i, 1) != null) {
                TeamA.add((String) (tableMatchesOverview.getValueAt(i, 1)));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error while parsing TeamA, corrupted cell: " + i + ",1");
            }

        }
        i = 0;
        LinkedList TeamB = new LinkedList();
        while (i < tableMatchesOverview.getModel().getRowCount()) {
            if (tableMatchesOverview.getValueAt(i, 2) != null) {
                TeamB.add((String) (tableMatchesOverview.getValueAt(i, 2)));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error while parsing TeamA, corrupted cell: " + i + ",2");
            }
        }
    }//GEN-LAST:event_btnMatchOverviewSaveActionPerformed

    private void btShowAllContestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowAllContestsActionPerformed
        viewContestController.showContests();
    }//GEN-LAST:event_btShowAllContestsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btShowAllContests;
    private javax.swing.JButton btnAddToContest;
    private javax.swing.JButton btnAddToSubTeam;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmContestTeams;
    private javax.swing.JButton btnConfirmSubTeam;
    private javax.swing.JButton btnContestNew;
    private javax.swing.JButton btnContestSave;
    private javax.swing.JButton btnMatchOverviewSave;
    private javax.swing.JButton btnRemoveFromContest;
    private javax.swing.JButton btnRemoveFromSubTeam;
    private javax.swing.JButton btnToA;
    private javax.swing.JButton btnToB;
    private javax.swing.JComboBox cmbContestContactDetails;
    private javax.swing.JComboBox cmbContestTeams;
    private com.toedter.calendar.JDateChooser dcContestEndDate;
    private com.toedter.calendar.JDateChooser dcContestStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList listboxAllContestTeams;
    private javax.swing.JList listboxAllTeamMembers;
    private javax.swing.JList listboxAllTeamsInSport;
    private javax.swing.JList listboxContestTeamMembers;
    private javax.swing.JList listboxContestTeams;
    private javax.swing.JList listboxShowContests;
    private javax.swing.JList listboxTeamA;
    private javax.swing.JList listboxTeamB;
    private javax.swing.JPanel panelContestHead;
    private javax.swing.JPanel panelContestLeft;
    private javax.swing.JPanel panelContestLocation;
    private javax.swing.JPanel panelContestMenu;
    private javax.swing.JPanel panelContestResults;
    private javax.swing.JPanel panelContestSubTeams;
    private javax.swing.JPanel panelContestTeams;
    private javax.swing.JPanel panelContestTeamsAlternate;
    private javax.swing.JPanel panelMembersList;
    private javax.swing.JPanel panelMembersSearch;
    private javax.swing.JSplitPane splitPanelContest;
    private javax.swing.JPanel splitPanelContestRight;
    private javax.swing.JSplitPane splitPanelMembersLeft;
    private javax.swing.JTabbedPane tabPanelContestDetails;
    private javax.swing.JTable tableMatchesOverview;
    private javax.swing.JTextField tfContestFee;
    private javax.swing.JTextField tfContestID;
    private javax.swing.JTextField tfContestMail1;
    private javax.swing.JTextField tfContestMail2;
    private javax.swing.JTextField tfContestName;
    private javax.swing.JTextField tfContestPhone1;
    private javax.swing.JTextField tfContestPhone2;
    private javax.swing.JTextField tfContestStreet;
    private javax.swing.JTextField tfContestStreetNumber;
    // End of variables declaration//GEN-END:variables

  
}
