/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package svm.view.forms;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.*;
import svm.view.controller.ViewMemberController;

/**
 *
 * @author Patrick
 */
public class PanelMembers extends javax.swing.JPanel {
     
    private ViewMemberController viewMemberController;

    public ViewMemberController getViewMemberController() {
        return viewMemberController;
    }

    /**
     * Creates new Form Panel for Member UseCases
     */  
    
    public PanelMembers() {       
            initComponents();
            this.viewMemberController = new ViewMemberController(this);
            addListeners();
             }
    
    /* Getters and Setters for Panel Components */

    public JButton getBtnMemberNew() {
        return btnMemberNew;
    }

    public JButton getBtnMemberSave() {
        return btnMemberSave;
    }

    public JButton getBtnMemberSearch() {
        return btnMemberSearch;
    }

    public JButton getBtnAddRole() {
        return btnAddRole;
    }

    public JButton getBtnRemoveRole() {
        return btnRemoveRole;
    }

    public JList getLibstboxActiveRoles() {
        return listboxActiveRoles;
    }

    public JList getLibstboxAllRoles() {
        return listboxAllRoles;
    }

    public JButton getBtnToggleSports() {
        return btnAddRole;
    }

    public JCheckBox getCbxSearchFee() {
        return cbxSearchFee;
    }

    public JComboBox getCmbContactDetails() {
        return cmbContactDetails;
    }

    public JComboBox getCmbGender() {
        return cmbGender;
    }

    public JComboBox getCmbSearchDepartment() {
        return cmbSearchDepartment;
    }

    public JDateChooser getDcBirthDate() {
        return dcBirthDate;
    }

    public JDateChooser getDcEntryDate() {
        return dcEntryDate;
    }

 

    public JTextField getTfFirstName() {
        return tfFirstName;
    }

    public JTextField getTfLastName() {
        return tfLastName;
    }

    public JTextField getTfMail1() {
        return tfMail1;
    }

    public JTextField getTfMail2() {
        return tfMail2;
    }


    public JTextField getTfPhone1() {
        return tfPhone1;
    }

    public JTextField getTfPhone2() {
        return tfPhone2;
    }

    public JTextField getTfSearchFirstName() {
        return tfSearchFirstName;
    }

    public JTextField getTfSearchLastName() {
        return tfSearchLastName;
    }

    public JTextField getTfSocialNumber() {
        return tfSocialNumber;
    }

    public JTextField getTfStreet() {
        return tfStreet;
    }

    public JTextField getTfStreetNumber() {
        return tfStreetNumber;
    }

    public JTextField getTfUserName() {
        return tfUserName;
    }

    public JCheckBox getCheckMemberFee() {
        return checkMemberFee;
    }
    
    public JComboBox getCmbSport() {
        return cmbSport;
    }
    
    private void addListeners() {
        
        this.addComponentListener(new ComponentListener() {

            @Override
            public void componentResized(ComponentEvent e) {
               
            }

            @Override
            public void componentMoved(ComponentEvent e) {
                
            }

            @Override
            public void componentShown(ComponentEvent e) {
               viewMemberController.searchMembers();
               viewMemberController.selectFirstMember();
           
            }

            @Override
            public void componentHidden(ComponentEvent e) {
               
            }
        });
    }
   
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanelMembers = new javax.swing.JSplitPane();
        panelMembersLeft = new javax.swing.JPanel();
        splitPanelMembersLeft = new javax.swing.JSplitPane();
        panelMembersSearch = new javax.swing.JPanel();
        cmbSearchDepartment = new javax.swing.JComboBox();
        tfSearchLastName = new javax.swing.JTextField();
        tfSearchFirstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxSearchFee = new javax.swing.JCheckBox();
        btnMemberSearch = new javax.swing.JButton();
        panelMembersList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listboxShowMembers = new javax.swing.JList();
        splitPanelMembersRight = new javax.swing.JPanel();
        panelMembersMenu = new javax.swing.JPanel();
        btnMemberSave = new javax.swing.JButton();
        btnMemberNew = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        tfFirstName = new javax.swing.JTextField();
        tfSocialNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfPhone2 = new javax.swing.JTextField();
        tfPhone1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfMail2 = new javax.swing.JTextField();
        tfMail1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfStreetNumber = new javax.swing.JTextField();
        tfStreet = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox();
        tfUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dcBirthDate = new com.toedter.calendar.JDateChooser();
        dcEntryDate = new com.toedter.calendar.JDateChooser();
        cmbContactDetails = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        lblMemberRoles = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        listScrollAllRoles = new javax.swing.JScrollPane();
        listboxAllRoles = new javax.swing.JList();
        btnAddRole = new javax.swing.JButton();
        checkMemberFee = new javax.swing.JCheckBox();
        listScrollActiveRoles = new javax.swing.JScrollPane();
        listboxActiveRoles = new javax.swing.JList();
        lblAllRoles = new javax.swing.JLabel();
        btnRemoveRole = new javax.swing.JButton();
        lblActiveRoles = new javax.swing.JLabel();
        lblSport = new javax.swing.JLabel();
        cmbSport = new javax.swing.JComboBox();

        splitPanelMembers.setBackground(new java.awt.Color(252, 252, 252));
        splitPanelMembers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        splitPanelMembers.setDividerLocation(365);
        splitPanelMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        splitPanelMembers.setDoubleBuffered(true);

        panelMembersLeft.setBackground(new java.awt.Color(252, 252, 252));
        panelMembersLeft.setPreferredSize(new java.awt.Dimension(362, 550));

        splitPanelMembersLeft.setDividerLocation(170);
        splitPanelMembersLeft.setDividerSize(4);
        splitPanelMembersLeft.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPanelMembersLeft.setDoubleBuffered(true);
        splitPanelMembersLeft.setPreferredSize(new java.awt.Dimension(362, 540));

        cmbSearchDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abteilung wählen", "Item 2", "Item 3", "Item 4" }));
        cmbSearchDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbSearchDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSearchDepartmentItemStateChanged(evt);
            }
        });

        tfSearchLastName.setText("x");

        tfSearchFirstName.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Mitglieder suchen");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nachname");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Vorname");

        cbxSearchFee.setText("Mitgliedsbeitrag bezahlt");
        cbxSearchFee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxSearchFee.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbxSearchFeeStateChanged(evt);
            }
        });

        btnMemberSearch.setText("Suche");
        btnMemberSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMemberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMembersSearchLayout = new javax.swing.GroupLayout(panelMembersSearch);
        panelMembersSearch.setLayout(panelMembersSearchLayout);
        panelMembersSearchLayout.setHorizontalGroup(
            panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMembersSearchLayout.createSequentialGroup()
                        .addGroup(panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMembersSearchLayout.createSequentialGroup()
                                .addComponent(cbxSearchFee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMemberSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfSearchLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSearchFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMembersSearchLayout.createSequentialGroup()
                        .addComponent(cmbSearchDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMembersSearchLayout.setVerticalGroup(
            panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSearchDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearchLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearchFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMemberSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cbxSearchFee))
                .addContainerGap())
        );

        splitPanelMembersLeft.setTopComponent(panelMembersSearch);

        panelMembersList.setBackground(new java.awt.Color(252, 252, 252));

        jScrollPane1.setBorder(null);
        jScrollPane1.setDoubleBuffered(true);

        listboxShowMembers.setBackground(new java.awt.Color(252, 252, 252));
        listboxShowMembers.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        listboxShowMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxShowMembers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listboxShowMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxShowMembers.setDoubleBuffered(true);
        listboxShowMembers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxShowMembersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listboxShowMembers);

        javax.swing.GroupLayout panelMembersListLayout = new javax.swing.GroupLayout(panelMembersList);
        panelMembersList.setLayout(panelMembersListLayout);
        panelMembersListLayout.setHorizontalGroup(
            panelMembersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        panelMembersListLayout.setVerticalGroup(
            panelMembersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        splitPanelMembersLeft.setRightComponent(panelMembersList);

        javax.swing.GroupLayout panelMembersLeftLayout = new javax.swing.GroupLayout(panelMembersLeft);
        panelMembersLeft.setLayout(panelMembersLeftLayout);
        panelMembersLeftLayout.setHorizontalGroup(
            panelMembersLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanelMembersLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        panelMembersLeftLayout.setVerticalGroup(
            panelMembersLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersLeftLayout.createSequentialGroup()
                .addComponent(splitPanelMembersLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        splitPanelMembers.setLeftComponent(panelMembersLeft);

        splitPanelMembersRight.setBackground(new java.awt.Color(252, 252, 252));

        panelMembersMenu.setBackground(new java.awt.Color(170, 216, 170));
        panelMembersMenu.setForeground(new java.awt.Color(255, 255, 255));

        btnMemberSave.setText("Save");
        btnMemberSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMemberSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberSaveActionPerformed(evt);
            }
        });

        btnMemberNew.setText("Neuer Eintrag");
        btnMemberNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMemberNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMembersMenuLayout = new javax.swing.GroupLayout(panelMembersMenu);
        panelMembersMenu.setLayout(panelMembersMenuLayout);
        panelMembersMenuLayout.setHorizontalGroup(
            panelMembersMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMemberSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMemberNew, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMembersMenuLayout.setVerticalGroup(
            panelMembersMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMembersMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMembersMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMemberSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnMemberNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Vorname *");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nachname *");

        tfLastName.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Sozialvers. *");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Geschlecht");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Geburtsdatum");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Adresse und Kontaktdetails");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Telefon 1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Telefon 2");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Email 1");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Email 2");

        tfStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStreetActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Straße");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nr.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Mitgliedsbeitrag");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Eintrittsdatum");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "m", "f" }));
        cmbGender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbGender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGenderItemStateChanged(evt);
            }
        });

        tfUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Benutzername *");

        dcBirthDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcBirthDatePropertyChange(evt);
            }
        });

        dcEntryDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcEntryDatePropertyChange(evt);
            }
        });

        cmbContactDetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6845 Hohenems" }));
        cmbContactDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbContactDetails.setFocusCycleRoot(true);
        cmbContactDetails.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbContactDetailsItemStateChanged(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Ort");

        lblMemberRoles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMemberRoles.setForeground(new java.awt.Color(102, 102, 102));
        lblMemberRoles.setText("Mitglied Rechteverwaltung");

        listboxAllRoles.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        listboxAllRoles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxAllRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxAllRoles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxAllRolesValueChanged(evt);
            }
        });
        listScrollAllRoles.setViewportView(listboxAllRoles);

        btnAddRole.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAddRole.setText(">");
        btnAddRole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoleActionPerformed(evt);
            }
        });

        checkMemberFee.setBackground(new java.awt.Color(252, 252, 252));
        checkMemberFee.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        checkMemberFee.setText("bezahlt");
        checkMemberFee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        listboxActiveRoles.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        listboxActiveRoles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxActiveRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxActiveRoles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxActiveRolesValueChanged(evt);
            }
        });
        listScrollActiveRoles.setViewportView(listboxActiveRoles);

        lblAllRoles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAllRoles.setForeground(new java.awt.Color(102, 102, 102));
        lblAllRoles.setText("Alle verfügbaren Rollen");

        btnRemoveRole.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnRemoveRole.setText("<");
        btnRemoveRole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveRoleActionPerformed(evt);
            }
        });

        lblActiveRoles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblActiveRoles.setForeground(new java.awt.Color(102, 102, 102));
        lblActiveRoles.setText("Aktive Rollen");

        lblSport.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblSport.setForeground(new java.awt.Color(51, 51, 51));
        lblSport.setText("Sportart");

        cmbSport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout splitPanelMembersRightLayout = new javax.swing.GroupLayout(splitPanelMembersRight);
        splitPanelMembersRight.setLayout(splitPanelMembersRightLayout);
        splitPanelMembersRightLayout.setHorizontalGroup(
            splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMembersMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, splitPanelMembersRightLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSocialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemberRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAllRoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(listScrollAllRoles))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemoveRole, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblActiveRoles)
                                    .addComponent(listScrollActiveRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcEntryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkMemberFee, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        splitPanelMembersRightLayout.setVerticalGroup(
            splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, splitPanelMembersRightLayout.createSequentialGroup()
                .addComponent(panelMembersMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSocialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                            .addComponent(tfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(checkMemberFee)
                                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(dcEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSport))
                        .addGap(21, 21, 21)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(dcBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)))))
                    .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                        .addComponent(lblMemberRoles)
                        .addGap(18, 18, 18)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAllRoles)
                            .addComponent(lblActiveRoles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(splitPanelMembersRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listScrollAllRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listScrollActiveRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(splitPanelMembersRightLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoveRole)))))
                .addGap(20, 20, 20))
        );

        splitPanelMembers.setRightComponent(splitPanelMembersRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanelMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanelMembers)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSearchFeeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbxSearchFeeStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSearchFeeStateChanged

    private void btnMemberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberSearchActionPerformed
               
        viewMemberController.searchMembers();
    }//GEN-LAST:event_btnMemberSearchActionPerformed

    private void listboxShowMembersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxShowMembersValueChanged
       viewMemberController.showMembers();
        
    }//GEN-LAST:event_listboxShowMembersValueChanged

    private void btnMemberSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberSaveActionPerformed
       viewMemberController.saveMember();
       viewMemberController.clearMemberList();
       viewMemberController.showMembers();
       viewMemberController.searchMembers();
    }//GEN-LAST:event_btnMemberSaveActionPerformed

    private void btnMemberNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberNewActionPerformed
        viewMemberController.createNewMember();       
        
    }//GEN-LAST:event_btnMemberNewActionPerformed

    private void dcBirthDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcBirthDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dcBirthDatePropertyChange

    private void cmbGenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGenderItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderItemStateChanged

    private void dcEntryDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcEntryDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dcEntryDatePropertyChange

    private void cmbContactDetailsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbContactDetailsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbContactDetailsItemStateChanged

    private void btnAddRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoleActionPerformed
        viewMemberController.addPrivilege();
    }//GEN-LAST:event_btnAddRoleActionPerformed

    private void listboxAllRolesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxAllRolesValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxAllRolesValueChanged

    private void listboxActiveRolesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxActiveRolesValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxActiveRolesValueChanged

    private void tfStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStreetActionPerformed

    private void cmbSearchDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSearchDepartmentItemStateChanged
        
    }//GEN-LAST:event_cmbSearchDepartmentItemStateChanged

    private void btnRemoveRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveRoleActionPerformed
        viewMemberController.removePrivilege();
    }//GEN-LAST:event_btnRemoveRoleActionPerformed

    public JLabel getLblActiveRoles() {
        return lblActiveRoles;
    }

    public JLabel getLblAllRoles() {
        return lblAllRoles;
    }

    public JLabel getLblMemberRoles() {
        return lblMemberRoles;
    }

    public JList getListboxActiveRoles() {
        return listboxActiveRoles;
    }

    public JList getListboxAllRoles() {
        return listboxAllRoles;
    }

    public JList getListboxShowMembers() {
        return listboxShowMembers;
    }

    public JScrollPane getListScrollActiveRoles() {
        return listScrollActiveRoles;
    }

    public JScrollPane getListScrollAllRoles() {
        return listScrollAllRoles;
    }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRole;
    private javax.swing.JButton btnMemberNew;
    private javax.swing.JButton btnMemberSave;
    private javax.swing.JButton btnMemberSearch;
    private javax.swing.JButton btnRemoveRole;
    private javax.swing.JCheckBox cbxSearchFee;
    private javax.swing.JCheckBox checkMemberFee;
    private javax.swing.JComboBox cmbContactDetails;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmbSearchDepartment;
    private javax.swing.JComboBox cmbSport;
    private com.toedter.calendar.JDateChooser dcBirthDate;
    private com.toedter.calendar.JDateChooser dcEntryDate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveRoles;
    private javax.swing.JLabel lblAllRoles;
    private javax.swing.JLabel lblMemberRoles;
    private javax.swing.JLabel lblSport;
    private javax.swing.JScrollPane listScrollActiveRoles;
    private javax.swing.JScrollPane listScrollAllRoles;
    private javax.swing.JList listboxActiveRoles;
    private javax.swing.JList listboxAllRoles;
    private javax.swing.JList listboxShowMembers;
    private javax.swing.JPanel panelMembersLeft;
    private javax.swing.JPanel panelMembersList;
    private javax.swing.JPanel panelMembersMenu;
    private javax.swing.JPanel panelMembersSearch;
    private javax.swing.JSplitPane splitPanelMembers;
    private javax.swing.JSplitPane splitPanelMembersLeft;
    private javax.swing.JPanel splitPanelMembersRight;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfMail1;
    private javax.swing.JTextField tfMail2;
    private javax.swing.JTextField tfPhone1;
    private javax.swing.JTextField tfPhone2;
    private javax.swing.JTextField tfSearchFirstName;
    private javax.swing.JTextField tfSearchLastName;
    private javax.swing.JTextField tfSocialNumber;
    private javax.swing.JTextField tfStreet;
    private javax.swing.JTextField tfStreetNumber;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables

   
}
