/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package svm.view.forms;

import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import svm.view.controller.ViewContestController;

/**
 *
 * @author Patrick
 */
public class PanelContests extends javax.swing.JPanel {

      private ViewContestController viewContestController;
    
    
    /**
     * Creates new Form Panel for Contest UseCases
     */
    public PanelContests() {
        this.viewContestController = new ViewContestController(this);
        initComponents();
        this.viewContestController.initializeModels();
        this.viewContestController.getAllSports();
    }

    public JTabbedPane getTabPanelContestDetails() {
        return tabPanelContestDetails;
    }

    /**
     * Getters and Setters for Components on Panel Contest *
     */
    public JButton getBtnAddToContest() {
        return btnAddToContest;
    }

    public JButton getBtnAddToSubTeam() {
        return btnAddToSubTeam;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnConfirmContestTeams() {
        return btnConfirmContestTeams;
    }

    public JButton getBtnConfirmSubTeam() {
        return btnConfirmSubTeam;
    }

    public JButton getBtnContestNew() {
        return btnContestNew;
    }


    public JButton getBtnContestSave() {
        return btnContestSave;
    }

    public JButton getBtnRemoveFromContest() {
        return btnRemoveFromContest;
    }

    public JButton getBtnRemoveFromSubTeam() {
        return btnRemoveFromSubTeam;
    }

    public JButton getBtnToA() {
        return btnToA;
    }

    public JButton getBtnToB() {
        return btnToB;
    }


    public JComboBox getCmbContestTeams() {
        return cmbContestTeams;
    }

   
    public JDateChooser getDcContestEndDate() {
        return dcContestEndDate;
    }

   

    public JDateChooser getDcContestStartDate() {
        return dcContestStartDate;
    }

    public JList getListboxAllContestTeams() {
        return listboxAllContestTeams;
    }

    public JList getListboxAllTeamMembers() {
        return listboxAllTeamMembers;
    }

    public JList getListboxAllTeamsInSport() {
        return listboxAllTeamsInSport;
    }

    public JList getListboxContestTeamMembers() {
        return listboxContestTeamMembers;
    }

    public JList getListboxContestTeams() {
        return listboxContestTeams;
    }

    public JList getListboxShowContests() {
        return listboxShowContests;
    }

    public JList getListboxTeamA() {
        return listboxTeamA;
    }

    public JList getListboxTeamB() {
        return listboxTeamB;
    }

    public JTable getTableMatchesOverview() {
        return tableMatchesOverview;
    }

    public JTextField getTfContestFee() {
        return tfContestFee;
    }

    public JTextField getTfContestName() {
        return tfContestName;
    }

    
    public JButton getBtnMatchCompositionSave() {
        return btnMatchCompositionSave;
    }

    public JButton getBtnMatchOverviewSave() {
        return btnMatchOverviewSave;
    }

    public JComboBox getCmbAllSports() {
        return cmbAllSports;
    }

    public JCheckBox getIsFinished() {
        return isFinished;
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanelContest = new javax.swing.JSplitPane();
        panelContestLeft = new javax.swing.JPanel();
        splitPanelMembersLeft = new javax.swing.JSplitPane();
        panelMembersSearch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMembersList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listboxShowContests = new javax.swing.JList();
        splitPanelContestRight = new javax.swing.JPanel();
        panelContestMenu = new javax.swing.JPanel();
        btnContestNew = new javax.swing.JButton();
        btnContestSave = new javax.swing.JButton();
        panelContestHead = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfContestFee = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfContestName = new javax.swing.JTextField();
        dcContestStartDate = new com.toedter.calendar.JDateChooser();
        dcContestEndDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbAllSports = new javax.swing.JComboBox();
        isFinished = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        tabPanelContestDetails = new javax.swing.JTabbedPane();
        panelContestTeams = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        listboxContestTeams = new javax.swing.JList();
        btnConfirmContestTeams = new javax.swing.JButton();
        btnRemoveFromContest = new javax.swing.JButton();
        btnAddToContest = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        listboxAllTeamsInSport = new javax.swing.JList();
        jLabel29 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        panelContestSubTeams = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cmbContestTeams = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        listboxAllTeamMembers = new javax.swing.JList();
        jLabel35 = new javax.swing.JLabel();
        btnRemoveFromSubTeam = new javax.swing.JButton();
        btnAddToSubTeam = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        listboxContestTeamMembers = new javax.swing.JList();
        btnConfirmSubTeam = new javax.swing.JButton();
        panelContestTeamsAlternate = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listboxAllContestTeams = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listboxTeamA = new javax.swing.JList();
        jLabel33 = new javax.swing.JLabel();
        btnToA = new javax.swing.JButton();
        btnToB = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listboxTeamB = new javax.swing.JList();
        jLabel39 = new javax.swing.JLabel();
        btnMatchCompositionSave = new javax.swing.JButton();
        panelContestResults = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableMatchesOverview = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        btnMatchOverviewSave = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(995, 690));

        splitPanelContest.setBackground(new java.awt.Color(252, 252, 252));
        splitPanelContest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        splitPanelContest.setDividerLocation(364);
        splitPanelContest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        splitPanelContest.setDoubleBuffered(true);

        panelContestLeft.setBackground(new java.awt.Color(252, 252, 252));
        panelContestLeft.setPreferredSize(new java.awt.Dimension(352, 500));

        splitPanelMembersLeft.setDividerLocation(60);
        splitPanelMembersLeft.setDividerSize(4);
        splitPanelMembersLeft.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPanelMembersLeft.setDoubleBuffered(true);
        splitPanelMembersLeft.setPreferredSize(new java.awt.Dimension(352, 500));

        panelMembersSearch.setPreferredSize(new java.awt.Dimension(350, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Aktuelle Wettbewerbe");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout panelMembersSearchLayout = new javax.swing.GroupLayout(panelMembersSearch);
        panelMembersSearch.setLayout(panelMembersSearchLayout);
        panelMembersSearchLayout.setHorizontalGroup(
            panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(128, 128, 128))
        );
        panelMembersSearchLayout.setVerticalGroup(
            panelMembersSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        splitPanelMembersLeft.setTopComponent(panelMembersSearch);

        panelMembersList.setBackground(new java.awt.Color(252, 252, 252));

        jScrollPane1.setBorder(null);
        jScrollPane1.setDoubleBuffered(true);

        listboxShowContests.setBackground(new java.awt.Color(252, 252, 252));
        listboxShowContests.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        listboxShowContests.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxShowContests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxShowContests.setDoubleBuffered(true);
        listboxShowContests.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxShowContestsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listboxShowContests);

        javax.swing.GroupLayout panelMembersListLayout = new javax.swing.GroupLayout(panelMembersList);
        panelMembersList.setLayout(panelMembersListLayout);
        panelMembersListLayout.setHorizontalGroup(
            panelMembersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMembersListLayout.setVerticalGroup(
            panelMembersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembersListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(281, 281, 281))
        );

        splitPanelMembersLeft.setRightComponent(panelMembersList);

        javax.swing.GroupLayout panelContestLeftLayout = new javax.swing.GroupLayout(panelContestLeft);
        panelContestLeft.setLayout(panelContestLeftLayout);
        panelContestLeftLayout.setHorizontalGroup(
            panelContestLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanelMembersLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );
        panelContestLeftLayout.setVerticalGroup(
            panelContestLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestLeftLayout.createSequentialGroup()
                .addComponent(splitPanelMembersLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        splitPanelContest.setLeftComponent(panelContestLeft);

        splitPanelContestRight.setBackground(new java.awt.Color(252, 252, 252));
        splitPanelContestRight.setPreferredSize(new java.awt.Dimension(0, 0));

        panelContestMenu.setBackground(new java.awt.Color(170, 216, 170));
        panelContestMenu.setForeground(new java.awt.Color(255, 255, 255));

        btnContestNew.setText("Neuer Eintrag");
        btnContestNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContestNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContestNewActionPerformed(evt);
            }
        });

        btnContestSave.setText("Save");
        btnContestSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContestSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContestSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContestMenuLayout = new javax.swing.GroupLayout(panelContestMenu);
        panelContestMenu.setLayout(panelContestMenuLayout);
        panelContestMenuLayout.setHorizontalGroup(
            panelContestMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnContestSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContestNew, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        panelContestMenuLayout.setVerticalGroup(
            panelContestMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnContestSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnContestNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelContestHead.setBackground(new java.awt.Color(252, 252, 252));
        panelContestHead.setPreferredSize(new java.awt.Dimension(560, 128));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ende");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Teilnahmebetrag");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("€");

        dcContestStartDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcContestStartDatePropertyChange(evt);
            }
        });

        dcContestEndDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcContestEndDatePropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Beginn");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bezeichnung");

        cmbAllSports.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sportart wählen" }));

        isFinished.setBackground(new java.awt.Color(252, 252, 252));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("abgeschlossen");

        javax.swing.GroupLayout panelContestHeadLayout = new javax.swing.GroupLayout(panelContestHead);
        panelContestHead.setLayout(panelContestHeadLayout);
        panelContestHeadLayout.setHorizontalGroup(
            panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestHeadLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcContestStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfContestFee, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(panelContestHeadLayout.createSequentialGroup()
                        .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelContestHeadLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcContestEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(isFinished, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelContestHeadLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfContestName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbAllSports, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelContestHeadLayout.setVerticalGroup(
            panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestHeadLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfContestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAllSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfContestFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel5)
                        .addComponent(jLabel19))
                    .addComponent(dcContestStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dcContestEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContestHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(isFinished, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanelContestDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabPanelContestDetails.setName(""); // NOI18N
        tabPanelContestDetails.setPreferredSize(new java.awt.Dimension(0, 0));
        tabPanelContestDetails.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPanelContestDetailsStateChanged(evt);
            }
        });

        panelContestTeams.setBackground(new java.awt.Color(252, 252, 252));
        panelContestTeams.setName("Teams"); // NOI18N

        listboxContestTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxContestTeams.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxContestTeamsValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(listboxContestTeams);

        btnConfirmContestTeams.setText("Wettkampfteams einladen");
        btnConfirmContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmContestTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmContestTeamsActionPerformed(evt);
            }
        });

        btnRemoveFromContest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoveFromContest.setText("<<");
        btnRemoveFromContest.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnRemoveFromContest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromContestActionPerformed(evt);
            }
        });

        btnAddToContest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddToContest.setText(">>");
        btnAddToContest.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnAddToContest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToContestActionPerformed(evt);
            }
        });

        listboxAllTeamsInSport.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxAllTeamsInSport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxAllTeamsInSport.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxAllTeamsInSportValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(listboxAllTeamsInSport);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Teams zum Wettkampf zuteilen");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Alle Teams");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Teams im Wettkampf");

        javax.swing.GroupLayout panelContestTeamsLayout = new javax.swing.GroupLayout(panelContestTeams);
        panelContestTeams.setLayout(panelContestTeamsLayout);
        panelContestTeamsLayout.setHorizontalGroup(
            panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContestTeamsLayout.createSequentialGroup()
                        .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemoveFromContest, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddToContest, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirmContestTeams)))))
                .addGap(10, 10, 10))
        );
        panelContestTeamsLayout.setVerticalGroup(
            panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContestTeamsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel29)
                .addGap(43, 43, 43)
                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(panelContestTeamsLayout.createSequentialGroup()
                        .addGroup(panelContestTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmContestTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContestTeamsLayout.createSequentialGroup()
                                .addComponent(btnAddToContest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveFromContest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabPanelContestDetails.addTab("Teams", panelContestTeams);

        panelContestSubTeams.setBackground(new java.awt.Color(252, 252, 252));
        panelContestSubTeams.setName("Wettkampfteilnehmer"); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Team für den Wettkampf zusammenstellen");

        cmbContestTeams.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmbContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbContestTeams.setFocusCycleRoot(true);
        cmbContestTeams.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbContestTeamsItemStateChanged(evt);
            }
        });
        cmbContestTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbContestTeamsActionPerformed(evt);
            }
        });

        listboxAllTeamMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxAllTeamMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxAllTeamMembers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxAllTeamMembersValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(listboxAllTeamMembers);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Alle Teammitglieder");

        btnRemoveFromSubTeam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoveFromSubTeam.setText("<<");
        btnRemoveFromSubTeam.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnRemoveFromSubTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromSubTeamActionPerformed(evt);
            }
        });

        btnAddToSubTeam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddToSubTeam.setText(">>");
        btnAddToSubTeam.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnAddToSubTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToSubTeamActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Wettkampfteam");

        listboxContestTeamMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxContestTeamMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxContestTeamMembers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxContestTeamMembersValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(listboxContestTeamMembers);

        btnConfirmSubTeam.setText("Wettkampfteam speichern");
        btnConfirmSubTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmSubTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSubTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContestSubTeamsLayout = new javax.swing.GroupLayout(panelContestSubTeams);
        panelContestSubTeams.setLayout(panelContestSubTeamsLayout);
        panelContestSubTeamsLayout.setHorizontalGroup(
            panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                        .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbContestTeams, javax.swing.GroupLayout.Alignment.LEADING, 0, 161, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemoveFromSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddToSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirmSubTeam)))))
                .addContainerGap())
        );
        panelContestSubTeamsLayout.setVerticalGroup(
            panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbContestTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestSubTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(panelContestSubTeamsLayout.createSequentialGroup()
                        .addComponent(btnAddToSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveFromSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfirmSubTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabPanelContestDetails.addTab("Wettkampfteilnehmer", panelContestSubTeams);

        panelContestTeamsAlternate.setBackground(new java.awt.Color(252, 252, 252));
        panelContestTeamsAlternate.setName("Neue Matches anlegen"); // NOI18N
        panelContestTeamsAlternate.setPreferredSize(new java.awt.Dimension(950, 364));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Wettkampf-Matches einteilen");

        listboxAllContestTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxAllContestTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listboxAllContestTeams.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxAllContestTeamsValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(listboxAllContestTeams);

        listboxTeamA.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxTeamA.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxTeamAValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listboxTeamA);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Team A");

        btnToA.setText(">> A");
        btnToA.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnToA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToAActionPerformed(evt);
            }
        });

        btnToB.setText(">> B");
        btnToB.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnToB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToBActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Team B");

        btnBack.setText("<<");
        btnBack.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        listboxTeamB.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listboxTeamB.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listboxTeamBValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(listboxTeamB);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Alle Teams im Wettkampf");

        btnMatchCompositionSave.setText("Wettkampfeinteilung speichern");
        btnMatchCompositionSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatchCompositionSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchCompositionSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContestTeamsAlternateLayout = new javax.swing.GroupLayout(panelContestTeamsAlternate);
        panelContestTeamsAlternate.setLayout(panelContestTeamsAlternateLayout);
        panelContestTeamsAlternateLayout.setHorizontalGroup(
            panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnToB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnToA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel39))
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnMatchCompositionSave)))
                .addGap(10, 10, 10))
        );
        panelContestTeamsAlternateLayout.setVerticalGroup(
            panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(btnMatchCompositionSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContestTeamsAlternateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestTeamsAlternateLayout.createSequentialGroup()
                        .addComponent(btnToA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnToB)
                        .addGap(44, 44, 44)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabPanelContestDetails.addTab("Neue Matches anlegen", panelContestTeamsAlternate);

        panelContestResults.setBackground(new java.awt.Color(252, 252, 252));
        panelContestResults.setName("Matchübersicht"); // NOI18N

        tableMatchesOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Team A", "Team B", "Score A", "Score B"
            }
        ));
        tableMatchesOverview.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jScrollPane8.setViewportView(tableMatchesOverview);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Matchübersicht und Resultate");

        btnMatchOverviewSave.setText("Matchübersicht speichern");
        btnMatchOverviewSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatchOverviewSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchOverviewSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContestResultsLayout = new javax.swing.GroupLayout(panelContestResults);
        panelContestResults.setLayout(panelContestResultsLayout);
        panelContestResultsLayout.setHorizontalGroup(
            panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestResultsLayout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMatchOverviewSave, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelContestResultsLayout.setVerticalGroup(
            panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestResultsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelContestResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(btnMatchOverviewSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanelContestDetails.addTab("Matchübersicht", panelContestResults);

        javax.swing.GroupLayout splitPanelContestRightLayout = new javax.swing.GroupLayout(splitPanelContestRight);
        splitPanelContestRight.setLayout(splitPanelContestRightLayout);
        splitPanelContestRightLayout.setHorizontalGroup(
            splitPanelContestRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContestMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPanelContestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelContestHead, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        splitPanelContestRightLayout.setVerticalGroup(
            splitPanelContestRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splitPanelContestRightLayout.createSequentialGroup()
                .addComponent(panelContestMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContestHead, 97, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanelContestDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        splitPanelContest.setRightComponent(splitPanelContestRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanelContest, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanelContest, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listboxShowContestsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxShowContestsValueChanged
        viewContestController.contestChange();
        viewContestController.updateContests();
        viewContestController.contestDetailsTabChanged();
    }//GEN-LAST:event_listboxShowContestsValueChanged

    private void dcContestStartDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcContestStartDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dcContestStartDatePropertyChange

    private void dcContestEndDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcContestEndDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dcContestEndDatePropertyChange

    private void tabPanelContestDetailsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPanelContestDetailsStateChanged
       viewContestController.contestDetailsTabChanged();
    }//GEN-LAST:event_tabPanelContestDetailsStateChanged

    private void btnMatchOverviewSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchOverviewSaveActionPerformed
        viewContestController.saveMatchOverview();
    }//GEN-LAST:event_btnMatchOverviewSaveActionPerformed

    private void btnConfirmSubTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSubTeamActionPerformed
        viewContestController.saveSubteam();
    }//GEN-LAST:event_btnConfirmSubTeamActionPerformed

    private void listboxContestTeamMembersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxContestTeamMembersValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxContestTeamMembersValueChanged

    private void btnAddToSubTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToSubTeamActionPerformed
        viewContestController.addToSubTeam();
    }//GEN-LAST:event_btnAddToSubTeamActionPerformed

    private void btnRemoveFromSubTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromSubTeamActionPerformed
        viewContestController.removeFromSubTeam();
    }//GEN-LAST:event_btnRemoveFromSubTeamActionPerformed

    private void listboxAllTeamMembersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxAllTeamMembersValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxAllTeamMembersValueChanged

    private void cmbContestTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbContestTeamsActionPerformed
        viewContestController.changeContestTeamSelection();
    }//GEN-LAST:event_cmbContestTeamsActionPerformed

    private void cmbContestTeamsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbContestTeamsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbContestTeamsItemStateChanged

    private void listboxAllTeamsInSportValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxAllTeamsInSportValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxAllTeamsInSportValueChanged

    private void btnAddToContestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToContestActionPerformed
        viewContestController.addTeamToContest();
    }//GEN-LAST:event_btnAddToContestActionPerformed

    private void btnRemoveFromContestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromContestActionPerformed
        viewContestController.removeTeamFromContest();
    }//GEN-LAST:event_btnRemoveFromContestActionPerformed

    private void btnConfirmContestTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmContestTeamsActionPerformed
        viewContestController.saveContestTeams();
    }//GEN-LAST:event_btnConfirmContestTeamsActionPerformed

    private void listboxContestTeamsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxContestTeamsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxContestTeamsValueChanged

    private void btnContestNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContestNewActionPerformed
        viewContestController.createNewContest();

    }//GEN-LAST:event_btnContestNewActionPerformed

    private void btnContestSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContestSaveActionPerformed
        viewContestController.saveContest();
        viewContestController.resetShowContestsDone();
        viewContestController.showContests();
    }//GEN-LAST:event_btnContestSaveActionPerformed

    private void btnMatchCompositionSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchCompositionSaveActionPerformed
        viewContestController.saveTeamComposition();
    }//GEN-LAST:event_btnMatchCompositionSaveActionPerformed

    private void listboxTeamBValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxTeamBValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxTeamBValueChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        viewContestController.removeFromTeam();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnToBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToBActionPerformed
        viewContestController.addToTeamB();
    }//GEN-LAST:event_btnToBActionPerformed

    private void btnToAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToAActionPerformed
        viewContestController.addToTeamA();
    }//GEN-LAST:event_btnToAActionPerformed

    private void listboxTeamAValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxTeamAValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxTeamAValueChanged

    private void listboxAllContestTeamsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listboxAllContestTeamsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listboxAllContestTeamsValueChanged

    public ViewContestController getViewContestController() {
        return viewContestController;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToContest;
    private javax.swing.JButton btnAddToSubTeam;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmContestTeams;
    private javax.swing.JButton btnConfirmSubTeam;
    private javax.swing.JButton btnContestNew;
    private javax.swing.JButton btnContestSave;
    private javax.swing.JButton btnMatchCompositionSave;
    private javax.swing.JButton btnMatchOverviewSave;
    private javax.swing.JButton btnRemoveFromContest;
    private javax.swing.JButton btnRemoveFromSubTeam;
    private javax.swing.JButton btnToA;
    private javax.swing.JButton btnToB;
    private javax.swing.JComboBox cmbAllSports;
    private javax.swing.JComboBox cmbContestTeams;
    private com.toedter.calendar.JDateChooser dcContestEndDate;
    private com.toedter.calendar.JDateChooser dcContestStartDate;
    private javax.swing.JCheckBox isFinished;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList listboxAllContestTeams;
    private javax.swing.JList listboxAllTeamMembers;
    private javax.swing.JList listboxAllTeamsInSport;
    private javax.swing.JList listboxContestTeamMembers;
    private javax.swing.JList listboxContestTeams;
    private javax.swing.JList listboxShowContests;
    private javax.swing.JList listboxTeamA;
    private javax.swing.JList listboxTeamB;
    private javax.swing.JPanel panelContestHead;
    private javax.swing.JPanel panelContestLeft;
    private javax.swing.JPanel panelContestMenu;
    private javax.swing.JPanel panelContestResults;
    private javax.swing.JPanel panelContestSubTeams;
    private javax.swing.JPanel panelContestTeams;
    private javax.swing.JPanel panelContestTeamsAlternate;
    private javax.swing.JPanel panelMembersList;
    private javax.swing.JPanel panelMembersSearch;
    private javax.swing.JSplitPane splitPanelContest;
    private javax.swing.JPanel splitPanelContestRight;
    private javax.swing.JSplitPane splitPanelMembersLeft;
    private javax.swing.JTabbedPane tabPanelContestDetails;
    private javax.swing.JTable tableMatchesOverview;
    private javax.swing.JTextField tfContestFee;
    private javax.swing.JTextField tfContestName;
    // End of variables declaration//GEN-END:variables

  
}
